### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by captn3m0** [ashu17706/ashu17706.github.io#1]
I noticed the issue because the hackercouch build failed:

https://travis-ci.org/hackercouch/hackercouch/jobs/206946239

```
- ./_site/couches/zero8.html
  *  External link http://ashutoshtripathi.me/ failed: 404 No error
htmlproof 2.5.2 | Error:  HTML-Proofer found 1 failure!
```

Let us know if you'd want us to drop the website link.

**Comment by ashu17706** [comment]
that's bad.Do you want me to commit info with removed link, untill I fix this ?

**Comment by captn3m0** [comment]
How long until this is fixed? We don't have any other updates in the pipeline, so if you can fix anytime soon, we can wait (and prevent an edit and a revert)

**Comment by ashu17706** [comment]
Some redirection issue when I am trying to setup custom domain in repo.
That right. Let me dig into this and fix it.

**Comment by ashu17706** [comment]
Fixed. for now. I renamed the repo to my-github-username.github.io. So it fixed for now. 
But I wonder how I can make the previous arrangement work. Like serving [ashutoshtripathi.me](https://ashutoshtripathi.me) from repo **ashutoshtripathi.me**.
